version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: assessment

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "4000:4000"
    depends_on:
      - db
